### ISSUE TITLE
greta?

### ISSUE THREAD

**Issue by ignacio82** [earthlab/dockerfiles#6]
Would you consider adding [greta](https://greta-dev.github.io/greta/get_started.html) to your dockerfile?

**Comment by mbjoseph** [comment]
Hi @ignacio82! Which Dockerfile are you using? We have one in each of these subdirectories.

**Comment by ignacio82** [comment]
The one I found with my first google search is [r-tensorflow](https://github.com/earthlab/dockerfiles/blob/master/r-tensorflow/Dockerfile) . That said, I'm not using it yet (this will be a weekend project :-) )

**Comment by mbjoseph** [comment]
Cool! Here you go @ignacio82 (see commit dd1919766a6c8cd549a3c57c8aeea134c818d2f5): https://hub.docker.com/r/earthlab/r-greta/

Happy greta-ing!

**Comment by ignacio82** [comment]
Thanks @mbjoseph . Is there a way to change the dockerfile so I can use greta with a user other than rstudio? For example, I want to be able to run something like:

```
docker run -d --restart=always  -p 8787:8787 --name="Rstudio" -e USER='ignacio' -e PASSWORD='MYSUPERSECRETPASSWORD!!' earthlab/r-tensorflow

```

**Comment by mbjoseph** [comment]
Hey @ignacio82 - AFAIK you can use the --user argument to change the user, but since everything is installed for the "rstudio" user, it's possible that you'll run into problems with things not being installed for an arbitrary user. I don't think we'll change our Dockerfile, since "rstudio" is general enough to work for everyone, but if you really needed to have your user name instead, you would need to go all the way back to the rocker/rstudio image's parent image and start from there.
